### ISSUE TITLE
clarify files that are generated to not be included in repo

### ISSUE THREAD

**Issue by electricherd** [shekohex/flutterust#10]
Awesome repo btw :wink:  :+1: 

the files
flutterust/packages/\*_ffi/lib/ffi.dart
and
flutterust/native/\*-ffi/binding.h

are generated and could be confused to be edited manually.
If you could delete them and ignore them via .gitignore somewhere, it's just a small improvement.
If you'd like you could give me access, and I'd do it myself and send a pull request.

Thanks for github actions plan, I had a travis build (very slow, not so good and not complete) done almost the same time when you introduced it yourself - but I still need to figure out as I have problems with the github actions yet! :+1:

**Comment by shekohex** [comment]
Thanks 😄.
> If you could delete them and ignore them via .gitignore somewhere, it's just a small improvement.

For these generated files, they are included here just for the reader to see through how it works, this repo act as a template or a guide on how to write Rust + Flutter applications.
So in real-world apps with a lot of contributors to the same codebase, it should be excluded as you said in the `.gitignore` file, but for us, it is really simple, and no need to do so. 😅 

Feel free to open a new issue to discuss any problems to help you build your GitHub actions based on the ones we have here :)
Also for more advanced one with a lot of options, see https://github.com/sunshine-protocol/sunscreen/tree/master/.github/workflows

**Comment by electricherd** [comment]
You're welcome ... flutterust was exactly what I was looking for weeks ago and a perfect match :grinning:  thank you!

I get your point, my proposal for a compromise would be to change the commentary inside these generated files as it is already in other files - that clearly show in the top of the files: 
//  Generated file. Do not edit.
and maybe ... as you stated, is included in git repository because to show the functionality without building it, like
//  Generated file. Do not edit. It is included here due to demonstration purpose. Add to .gitignore in your own repo.

You can either change it in the generation of the files or in the in the "starting" files in the repo, which would be overwritten anyhow?
Anyhow it's not the most important thing.

I would also recommend to add links to your great descriptions in the readme of this repo:
https://dev.to/sunshine-chain/dart-meets-rust-a-match-made-in-heaven-9f5
https://dev.to/sunshine-chain/rust-and-dart-the-async-story-3adk
(only if you want to be shy about it, or want to hide it :wink: )

Thank you very much for the link to the github actions, I will have a look there!
