### ISSUE TITLE
Hi, is there a man page for this?

### ISSUE THREAD

**Issue by Joe23232** [shekohex/flutterust#12]
Hi, are there any man pages available?

Additionally is it harder to use Flutterrust over Flutter dart?

**Comment by shekohex** [comment]
Hello @Joe23232 
No, there are no man pages for this, why should be? 😅 

Also, this is not by any means a replacement for Flutter with Dart!
Just to be clear, this a template where you can write truly native plugins with maximum performance for Flutter applications using Rust.

For example, if your application is doing a lot of image processing and it acts slow, you could write a plugin in Rust and say for example you could use the [image](https://crates.io/crates/image) crate in it and expose some functions to do what you need to the Dart/Flutter side from Rust (FFI) and you got now a fast image processing.

**Comment by Joe23232** [comment]
Ah I see, thanks mate :)

**Comment by shekohex** [comment]
Yes, it is used along with Flutter/Dart.

Here are a few examples:

Sunshine: [Sunscreen](https://github.com/sunshine-protocol/sunscreen)
Edgeware: [Edgeware Wallet](https://github.com/edgeware-builders/edgeware-wallet)
[Owlchat](https://github.com/owlchat/): (Private, Still under construction).

**Comment by Joe23232** [comment]
I see, thanks mate :)

Sorry to ask you this but like do you know how do I get started with pure Rust with Android? I know that Rust can be used to call APIs. But how would I get started?

**Comment by shekohex** [comment]
One of our contributors (@i-schuetz) is working on [this repo](https://github.com/i-schuetz/rust_android_ios) where you could use Rust inside Android/iOS separately without using Flutter.
you should check it out!

**Comment by Joe23232** [comment]
Thanks mate for the link, I appreciate it :)

**Comment by shekohex** [comment]
Happy to help, feel free to close this issue if it solved your questions!

**Comment by Joe23232** [comment]
Thanks mate, will do :)
