### ISSUE TITLE
How to handle error when calling async function

### ISSUE THREAD

**Issue by yiv** [shekohex/flutterust#15]
```
use allo_isolate::Isolate;



#[no_mangle]
pub extern "C" fn load_page(port: i64, url: *const raw::c_char) -> i32 {
    // get a ref to the runtime
    let rt = runtime!();
    let url = cstr!(url);
    rt.spawn(async move {
        // load the page and get the result back
        let result = scrap::load_page(url).await;
        // make a ref to an isolate using it's port
        let isolate = Isolate::new(port);
        // and sent it the `Rust's` result
        // no need to convert anything :)
        isolate.post(result);
    });
    1
}
```

If error occured on calling **scrap::load_page(url).await**, how to return the error back to flutter

**Comment by shekohex** [comment]
The value passed to `isolate.post(res)` is bonded by any type that implement `IntoDart` trait.
See: https://docs.rs/allo-isolate/0.1.7/allo_isolate/trait.IntoDart.html

So basically, you can implement it for your own types and customize how the result sent to Dart will look like.
And the trait is already implemented for most of Rust types (numbers, strings, lists, Option, Result, .. etc).

Speaking of `Result<T, E>` if T is Implemented `IntoDart` trait and E can be converted to a String (i.e `ToString`) then you should get your error messages back in Flutter.

The way I did it is not the best one, but I tell Dart to expect a value of type `T` and if it failed, I know there's an error somewhere so I convert the value to a String and throw it to the caller.

Want to play a bit and dive deeper?

Take this as an example: https://github.com/edgeware-builders/edgeware-wallet/blob/main/native/edgeware/src/lib.rs#L203

It's an async operation that may return an error, this another way to return raw pointers to the Dart side.
https://github.com/edgeware-builders/edgeware-wallet/blob/main/packages/edgeware/lib/edgeware.dart#L121

Happy hacking :)

**Comment by yiv** [comment]
You are the most enhusiastic maintainter I have ever met by far.
Your replies are very detailed and profissional.
Sincerely Appreciate

**Comment by shekohex** [comment]
Thank you!
Feel free to open a new issue if you faced any problems.
