### ISSUE TITLE
Callback example?

### ISSUE THREAD

**Issue by i-schuetz** [shekohex/flutterust#2]
Nice project! Sometimes (not necessarily for multithreading), it makes sense for the app to register a callback in Rust. E.g. I'm using this in native apps to send log messages to be displayed in a logs screen in the app. Could you add an example for this?

**Comment by shekohex** [comment]
Yes, we are using the same thing in our applications here in [`Frustylogger`](https://github.com/sunshine-protocol/frusty-logger)

> PS: it does not work with multithreading, as you cannot call a native dart function from other threads.
