### ISSUE TITLE
note: ld: error: unable to find library -lgcc

### ISSUE THREAD

**Issue by mlg-hub** [shekohex/flutterust#29]
Am trying to run the project on Ubuntu 20 and i am stuck at this error, when running cargo make:
note: ld: error: unable to find library -lgcc
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gianlucamazza** [comment]
I had your problem today.
I think is related to your Android SDK

![Schermata da 2021-08-20 16-49-34](https://user-images.githubusercontent.com/25006045/130251908-42c0d444-513a-4258-b631-5f87acb0dd90.png)

**Comment by mlg-hub** [comment]
Thanks. let me try it and  the issue once it works.
did it work for you?

**Comment by mlg-hub** [comment]
The error is due toNDK version. The solution that worked for me was to downgrade the NDK version to 20.0.*
