### ISSUE TITLE
libscrap_ffi.so not found

### ISSUE THREAD

**Issue by ghost** [shekohex/flutterust#48]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building Builder:
Invalid argument(s): Failed to load dynamic library 'libscrap_ffi.so': dlopen
failed: library
"libscrap_ffi.so" not found

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///home/StudioProjects/rust_flutter_app/flutterust/lib/
  main.dart:10:12

**Comment by ghost** [comment]
Hello, trying to create an app that uses rust as a backend and flutter as a front. I cloned your repo and ran the command for android, and then ran flutter run. I am running this on a linux ubuntu. Thanks!

**Comment by shekohex** [comment]
Hey, did you compile the code using `cargo make`?

**Comment by ghost** [comment]
hello sorry for not getting back sooner, I complied the code using cargo android build.

**Comment by ghost** [comment]
No worries though, CLI and the web versions are working great, and that's all I need for now. thanks

**Comment by shekohex** [comment]
Glad to hear that!
Also, you may want to take a look into more user-friendly solutions like https://github.com/fzyzcjy/flutter_rust_bridge

**Comment by ghost** [comment]
Ok cool thanks!
